# Shell Script CircleCI 2.0 configuration file
version: 2
#executorType: machine
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    environment:
      PROJECT_NAME: provisioning-app
      GOOGLE_PROJECT_ID: provisioning-253609
      GOOGLE_COMPUTE_ZONE: us-central1-b
      GOOGLE_CLUSTER_NAME: cluster-1
      DEPLOYMENT_MANAGER_NAME: deployment-with-2-vms
    steps:
      - checkout
      # Step: Create Virtual Machines
      - run:
          name: Create VM
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > service_key.txt
            base64 -i service_key.txt -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            EXISTING_DEPLOYMENT_MANAGER=$(gcloud deployment-manager deployments list --format="value(name)" --filter="name=$DEPLOYMENT_MANAGER_NAME")
            echo "${EXISTING_DEPLOYMENT_MANAGER}" "${DEPLOYMENT_MANAGER_NAME}"
            if [ "${EXISTING_DEPLOYMENT_MANAGER}" == "${DEPLOYMENT_MANAGER_NAME}" ]; then
              ./delete.sh
            fi
            ./create.sh
            
            #command: |
            #if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #fi
