# Shell Script CircleCI 2.0 configuration file
version: 2
executorType: machine
jobs:
  build:
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      # Step 1: Delete virtual machines
      - run:
          name: Delete VMs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./delete.sh
            fi
      # Step 2: Create virtual machines
      - run:
          name: Delete VMs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./create.sh
            fi
