# Shell Script CircleCI 2.0 configuration file
version: 2
#executorType: machine
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    environment:
      PROJECT_NAME: provisioning-app
      GOOGLE_PROJECT_ID: provisioning-253609
      GOOGLE_COMPUTE_ZONE: us-central1-b
      GOOGLE_CLUSTER_NAME: cluster-1
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > service_key.txt
            base64 -i service_key.txt -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            #EXISTING_CLUSTER=$(gcloud container clusters list --format="value(name)" --filter="name=$GOOGLE_CLUSTER_NAME")
            #if [ "${EXISTING_CLUSTER}" != $GOOGLE_CLUSTER_NAME ]
            #then
              # Create cluster if it doesn't already exist
              #  gcloud --quiet container clusters create $GOOGLE_CLUSTER_NAME --num-nodes=1
              #else
              #gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
              #fi
            
            #gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      # Step 1: Delete virtual machines
      - run:
          name: Delete VMs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./delete.sh
            fi
      # Step 2: Create virtual machines
      - run:
          name: Create VMs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./create.sh
            fi
